import vitest from '@vitest/eslint-plugin';
import perfectionist from 'eslint-plugin-perfectionist';
import prettier from 'eslint-plugin-prettier/recommended';
import promise from 'eslint-plugin-promise';
import regexp from 'eslint-plugin-regexp';
import sonarjs from 'eslint-plugin-sonarjs';
import unicorn from 'eslint-plugin-unicorn';
import globals from 'globals';
import typescript from 'typescript-eslint';

const SRC_GLOB = '**/*.{js,cjs,mjs,ts,cts,mts}';
const TYPESCRIPT_GLOB = '**/*.{ts,cts,mts}';
const TEST_GLOB = '**/*.{spec,test}.{js,mjs,cjs,ts,cts,mts}';
const CODE_STYLE_GLOB = '**/*.{js,mjs,cjs,ts,cts,mts,json}';

const ERROR = 'error';
const WARN = 'warn';
const OFF = 'off';

/** @type {import('eslint').Linter.Config[]} */
export default [
	{
		ignores: [
			'dist/**/*',
			'build/**/*',
			'**/node_modules/**/*',
			'__reports__/**/*',
			'schemas/**/*',
			'assets/**/*',
			'tests/env/**/*',
			'tests/run.js',
			'.vscode/**/*',
		],
	},

	// #region ecmascript
	{
		files: [SRC_GLOB],
		languageOptions: {
			ecmaVersion: 2023,
			globals: { ...globals.node },
			sourceType: 'module',
		},
		rules: {
			'array-callback-return': ERROR,
			complexity: [WARN, 15],
			'constructor-super': ERROR,
			'default-case': WARN,
			'default-case-last': WARN,
			'default-param-last': WARN,
			eqeqeq: WARN,
			'for-direction': ERROR,
			'func-style': [WARN, 'declaration', { allowArrowFunctions: true }],
			'getter-return': [ERROR, { allowImplicit: true }],
			'grouped-accessor-pairs': WARN,
			'max-classes-per-file': [WARN, { ignoreExpressions: true, max: 1 }],
			'max-params': [WARN, 5],
			'no-async-promise-executor': ERROR,
			'no-case-declarations': ERROR,
			'no-class-assign': ERROR,
			'no-compare-neg-zero': ERROR,
			'no-cond-assign': ERROR,
			'no-console': [WARN, { allow: ['info', ERROR, WARN] }],
			'no-const-assign': ERROR,
			'no-constant-binary-expression': ERROR,
			'no-constant-condition': ERROR,
			'no-control-regex': ERROR,
			'no-debugger': WARN,
			'no-delete-var': ERROR,
			'no-dupe-args': ERROR,
			'no-dupe-class-members': ERROR,
			'no-dupe-else-if': ERROR,
			'no-dupe-keys': ERROR,
			'no-duplicate-case': ERROR,
			'no-empty': ERROR,
			'no-empty-character-class': ERROR,
			'no-empty-pattern': ERROR,
			'no-empty-static-block': ERROR,
			'no-ex-assign': ERROR,
			'no-extra-boolean-cast': ERROR,
			'no-extra-label': WARN,
			'no-fallthrough': ERROR,
			'no-func-assign': ERROR,
			'no-global-assign': ERROR,
			'no-import-assign': ERROR,
			'no-invalid-regexp': ERROR,
			'no-irregular-whitespace': ERROR,
			'no-lonely-if': WARN,
			'no-loss-of-precision': ERROR,
			'no-misleading-character-class': ERROR,
			'no-mixed-spaces-and-tabs': [WARN, 'smart-tabs'],
			'no-new-native-nonconstructor': ERROR,
			'no-new-wrappers': WARN,
			'no-nonoctal-decimal-escape': ERROR,
			'no-obj-calls': ERROR,
			'no-octal': ERROR,
			'no-prototype-builtins': ERROR,
			'no-redeclare': ERROR,
			'no-regex-spaces': ERROR,
			'no-return-await': OFF,
			'no-self-assign': ERROR,
			'no-self-compare': WARN,
			'no-setter-return': ERROR,
			'no-shadow-restricted-names': ERROR,
			'no-sparse-arrays': ERROR,
			'no-this-before-super': ERROR,
			'no-throw-literal': ERROR,
			'no-undef': ERROR,
			'no-undef-init': WARN,
			'no-unexpected-multiline': ERROR,
			'no-unneeded-ternary': WARN,
			'no-unreachable': ERROR,
			'no-unreachable-loop': WARN,
			'no-unsafe-finally': ERROR,
			'no-unsafe-negation': ERROR,
			'no-unsafe-optional-chaining': ERROR,
			'no-unused-labels': WARN,
			'no-unused-private-class-members': WARN,
			'no-unused-vars': WARN,
			'no-useless-assignment': WARN,
			'no-useless-backreference': ERROR,
			'no-useless-catch': ERROR,
			'no-useless-computed-key': WARN,
			'no-useless-escape': ERROR,
			'no-useless-return': ERROR,
			'no-var': ERROR,
			'no-with': ERROR,
			'object-shorthand': WARN,
			'prefer-arrow-callback': WARN,
			'prefer-const': WARN,
			'prefer-exponentiation-operator': WARN,
			'prefer-promise-reject-errors': WARN,
			'prefer-regex-literals': WARN,
			'prefer-rest-params': WARN,
			'prefer-spread': WARN,
			'prefer-template': WARN,
			'quote-props': [WARN, 'as-needed'],
			radix: [WARN, 'as-needed'],
			// false-positive-prone on benign sequential async assignments
			'require-atomic-updates': OFF,
			'require-await': ERROR,
			// pedantic for this lib; risky on the schema.util validation regexes
			'require-unicode-regexp': OFF,
			'require-yield': ERROR,
			'use-isnan': ERROR,
			'valid-typeof': ERROR,
			yoda: WARN,
			'capitalized-comments': [
				WARN,
				'never',
				{
					block: { ignorePattern: '.*' },
					line: {
						ignoreConsecutiveComments: true,
						ignorePattern: '[A-Z]*:.*',
					},
				},
			],
			quotes: [
				WARN,
				'single',
				{
					allowTemplateLiterals: false,
					avoidEscape: true,
				},
			],
		},
	},
	// #endregion

	// #region typescript
	typescript.configs.strict[0],
	{
		files: [TYPESCRIPT_GLOB],
		languageOptions: {
			parserOptions: {
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
			},
		},
		rules: {
			...typescript.configs.strict[1].rules,
			...typescript.configs.strict[2].rules,
			'@typescript-eslint/explicit-function-return-type': OFF,
			'@typescript-eslint/explicit-module-boundary-types': OFF,
			'@typescript-eslint/no-empty-function': WARN,
			'@typescript-eslint/no-empty-object-type': OFF,
			'@typescript-eslint/no-explicit-any': OFF,
			'@typescript-eslint/no-extraneous-class': OFF,
			'@typescript-eslint/no-non-null-assertion': OFF,
			'@typescript-eslint/no-redundant-type-constituents': ERROR,
			'@typescript-eslint/no-unsafe-function-type': OFF,
			'@typescript-eslint/no-wrapper-object-types': WARN,
			'@typescript-eslint/return-await': [ERROR, 'in-try-catch'],
			'@typescript-eslint/consistent-type-imports': [
				WARN,
				{
					fixStyle: 'inline-type-imports',
					prefer: 'type-imports',
				},
			],
			'@typescript-eslint/no-empty-interface': [
				ERROR,
				{ allowSingleExtends: true },
			],
			'@typescript-eslint/no-floating-promises': [
				WARN,
				{
					ignoreVoid: true,
					checkThenables: true,
					ignoreIIFE: true,
				},
			],
			'@typescript-eslint/no-namespace': [
				WARN,
				{ allowDeclarations: true },
			],
			'@typescript-eslint/no-unused-vars': [
				WARN,
				{
					args: 'after-used',
					argsIgnorePattern: '^_.*',
					caughtErrors: 'all',
					caughtErrorsIgnorePattern: '^_.*',
					destructuredArrayIgnorePattern: '^_.*',
					ignoreRestSiblings: true,
					vars: 'local',
					varsIgnorePattern: '^_.*',
				},
			],
			'@typescript-eslint/no-use-before-define': [
				WARN,
				{
					classes: false,
					enums: true,
					functions: false,
					ignoreTypeReferences: true,
					typedefs: true,
					variables: true,
				},
			],
			'@typescript-eslint/sort-type-constituents': [
				WARN,
				{
					checkIntersections: true,
					checkUnions: true,
					groupOrder: [
						'named',
						'keyword',
						'operator',
						'literal',
						'function',
						'import',
						'conditional',
						'object',
						'tuple',
						'intersection',
						'union',
						'nullish',
					],
				},
			],
		},
	},
	// #endregion

	// #region sonar
	{
		files: [SRC_GLOB],
		plugins: { sonarjs },
		rules: {
			'sonarjs/cognitive-complexity': [WARN, 16],
			'sonarjs/max-switch-cases': [WARN, 12],
			'sonarjs/no-all-duplicated-branches': ERROR,
			'sonarjs/no-collapsible-if': ERROR,
			'sonarjs/no-collection-size-mischeck': ERROR,
			'sonarjs/no-duplicate-string': [WARN, { threshold: 5 }],
			'sonarjs/no-duplicated-branches': ERROR,
			'sonarjs/no-element-overwrite': ERROR,
			'sonarjs/no-identical-conditions': ERROR,
			'sonarjs/no-identical-expressions': ERROR,
			'sonarjs/no-identical-functions': ERROR,
			'sonarjs/no-ignored-return': ERROR,
			'sonarjs/no-inverted-boolean-check': ERROR,
			'sonarjs/no-nested-switch': ERROR,
			'sonarjs/no-nested-template-literals': ERROR,
			'sonarjs/no-redundant-boolean': ERROR,
			'sonarjs/no-same-line-conditional': ERROR,
			'sonarjs/no-small-switch': ERROR,
			'sonarjs/no-useless-catch': ERROR,
			'sonarjs/non-existent-operator': ERROR,
			'sonarjs/prefer-object-literal': ERROR,
			'sonarjs/prefer-single-boolean-return': ERROR,
			'sonarjs/prefer-while': ERROR,
		},
	},
	// #endregion

	// #region promise
	{
		files: [SRC_GLOB],
		plugins: { promise },
		rules: {
			'promise/always-return': OFF,
			'promise/avoid-new': OFF,
			'promise/catch-or-return': ERROR,
			'promise/no-callback-in-promise': OFF,
			'promise/no-multiple-resolved': ERROR,
			'promise/no-nesting': WARN,
			'promise/no-new-statics': ERROR,
			'promise/no-promise-in-callback': WARN,
			'promise/no-return-in-finally': WARN,
			'promise/no-return-wrap': WARN,
			'promise/param-names': WARN,
			'promise/prefer-await-to-then': WARN,
			'promise/valid-params': WARN,
		},
	},
	// #endregion

	// #region unicorn
	{
		files: [SRC_GLOB],
		plugins: { unicorn },
		rules: {
			'no-negated-condition': OFF,
			'no-nested-ternary': OFF,
			'unicorn/better-regex': WARN,
			'unicorn/catch-error-name': WARN,
			'unicorn/consistent-destructuring': ERROR,
			'unicorn/consistent-function-scoping': WARN,
			'unicorn/error-message': ERROR,
			'unicorn/escape-case': WARN,
			'unicorn/expiring-todo-comments': ERROR,
			'unicorn/explicit-length-check': WARN,
			'unicorn/new-for-builtins': ERROR,
			'unicorn/no-array-method-this-argument': ERROR,
			'unicorn/no-array-push-push': ERROR,
			'unicorn/no-await-expression-member': WARN,
			'unicorn/no-await-in-promise-methods': ERROR,
			'unicorn/no-console-spaces': WARN,
			'unicorn/no-empty-file': ERROR,
			'unicorn/no-for-each': WARN,
			'unicorn/no-hex-escape': WARN,
			'unicorn/no-instanceof-array': WARN,
			'unicorn/no-invalid-fetch-options': ERROR,
			'unicorn/no-lonely-if': WARN,
			'unicorn/no-magic-array-flat-depth': WARN,
			'unicorn/no-negated-condition': ERROR,
			'unicorn/no-new-array': ERROR,
			'unicorn/no-new-buffer': ERROR,
			// cLI tool: process.exit is part of the public command contract
			'unicorn/no-process-exit': OFF,
			'unicorn/no-single-promise-in-promise-methods': WARN,
			'unicorn/no-thenable': ERROR,
			'unicorn/no-this-assignment': WARN,
			'unicorn/no-typeof-undefined': WARN,
			'unicorn/no-unnecessary-await': ERROR,
			'unicorn/no-unreadable-array-destructuring': OFF,
			'unicorn/no-unreadable-iife': ERROR,
			'unicorn/no-unused-properties': WARN,
			'unicorn/no-useless-fallback-in-spread': ERROR,
			'unicorn/no-useless-length-check': WARN,
			'unicorn/no-useless-spread': WARN,
			'unicorn/no-useless-switch-case': WARN,
			'unicorn/no-useless-undefined': WARN,
			'unicorn/no-zero-fractions': WARN,
			'unicorn/number-literal-case': WARN,
			'unicorn/numeric-separators-style': WARN,
			'unicorn/prefer-array-find': WARN,
			'unicorn/prefer-array-flat': WARN,
			'unicorn/prefer-array-flat-map': WARN,
			'unicorn/prefer-array-index-of': WARN,
			'unicorn/prefer-array-some': WARN,
			'unicorn/prefer-blob-reading-methods': WARN,
			'unicorn/prefer-code-point': WARN,
			'unicorn/prefer-date-now': WARN,
			'unicorn/prefer-default-parameters': WARN,
			'unicorn/prefer-event-target': ERROR,
			'unicorn/prefer-export-from': WARN,
			'unicorn/prefer-includes': WARN,
			'unicorn/prefer-json-parse-buffer': WARN,
			'unicorn/prefer-logical-operator-over-ternary': WARN,
			'unicorn/prefer-math-trunc': WARN,
			'unicorn/prefer-modern-math-apis': WARN,
			'unicorn/prefer-module': ERROR,
			'unicorn/prefer-native-coercion-functions': WARN,
			'unicorn/prefer-negative-index': WARN,
			'unicorn/prefer-node-protocol': ERROR,
			'unicorn/prefer-number-properties': WARN,
			'unicorn/prefer-object-from-entries': WARN,
			'unicorn/prefer-prototype-methods': WARN,
			'unicorn/prefer-reflect-apply': WARN,
			'unicorn/prefer-regexp-test': WARN,
			'unicorn/prefer-set-has': WARN,
			'unicorn/prefer-set-size': WARN,
			'unicorn/prefer-spread': WARN,
			'unicorn/prefer-string-raw': WARN,
			'unicorn/prefer-string-replace-all': WARN,
			'unicorn/prefer-string-slice': WARN,
			'unicorn/prefer-string-starts-ends-with': WARN,
			'unicorn/prefer-string-trim-start-end': WARN,
			'unicorn/prefer-structured-clone': WARN,
			'unicorn/prefer-switch': WARN,
			'unicorn/prefer-top-level-await': OFF,
			'unicorn/prefer-type-error': WARN,
			'unicorn/prevent-abbreviations': OFF,
			'unicorn/require-array-join-separator': WARN,
			'unicorn/require-number-to-fixed-digits-argument': ERROR,
			'unicorn/string-content': WARN,
			'unicorn/template-indent': WARN,
			'unicorn/text-encoding-identifier-case': WARN,
			'unicorn/throw-new-error': ERROR,
			'unicorn/filename-case': [
				ERROR,
				{
					cases: { kebabCase: true, pascalCase: true },
				},
			],
		},
	},
	// #endregion

	// #region perfectionist
	{
		files: [SRC_GLOB],
		plugins: { perfectionist },
		rules: {
			'perfectionist/sort-array-includes': WARN,
			'perfectionist/sort-exports': WARN,
			'perfectionist/sort-heritage-clauses': WARN,
			'perfectionist/sort-maps': WARN,
			'perfectionist/sort-named-exports': WARN,
			'perfectionist/sort-named-imports': WARN,
			'perfectionist/sort-sets': WARN,
			'perfectionist/sort-variable-declarations': WARN,
			'perfectionist/sort-enums': [
				WARN,
				{ sortByValue: 'ifNumericEnum' },
			],
			'perfectionist/sort-imports': [
				WARN,
				{
					internalPattern: ['#*/*'],
					newlinesBetween: 'ignore',
					type: 'alphabetical',
					groups: [
						['type-builtin', 'builtin'],
						['type-subpath', 'subpath'],
						['type-external', 'external'],
						['type-internal', 'internal'],
						['type-parent', 'parent'],
						['type-sibling', 'sibling'],
						['type-index', 'index'],
						['type-import', 'import'],
						'style',
						'unknown',
					],
				},
			],
			'perfectionist/sort-interfaces': [
				WARN,
				{
					customGroups: [
						{ elementNamePattern: '.*([iI]d)$', groupName: 'top' },
					],
					groups: [
						'top',
						'member',
						'multiline-member',
						'multiline-optional-member',
						'optional-member',
						'method',
						'multiline-method',
						'multiline-optional-method',
						'optional-method',
						'unknown',
						'index-signature',
					],
				},
			],
			'perfectionist/sort-object-types': [
				WARN,
				{
					customGroups: [
						{ elementNamePattern: '.*([iI]d)$', groupName: 'top' },
					],
					groups: [
						'top',
						'member',
						'multiline-member',
						'multiline-optional-member',
						'optional-member',
						'method',
						'multiline-method',
						'multiline-optional-method',
						'optional-method',
						'unknown',
					],
				},
			],
			'perfectionist/sort-objects': [
				WARN,
				{
					type: 'unsorted',
					useConfigurationIf: {
						declarationMatchesPattern: '^(?:examples)$',
					},
				},
				{
					partitionByComment: '#region*',
					customGroups: [
						{ elementNamePattern: '.*([iI]d)$', groupName: 'top' },
					],
					groups: [
						'top',
						'member',
						'multiline-member',
						'method',
						'multiline-method',
						'unknown',
					],
				},
			],
		},
		settings: {
			perfectionist: {
				ignoreCase: false,
				newlinesInside: 'ignore',
				order: 'asc',
				partitionByNewLine: true,
				type: 'natural',
			},
		},
	},
	// #endregion

	// #region regexp
	{
		files: [SRC_GLOB],
		plugins: { regexp },
		rules: {
			...regexp.configs['flat/recommended'].rules,
		},
	},
	// #endregion

	// #region prettier
	{
		files: [CODE_STYLE_GLOB],
		...prettier,
		rules: { 'prettier/prettier': WARN },
	},
	// #endregion

	// #region vitest
	{
		files: [TEST_GLOB],
		plugins: { vitest },
		rules: {
			// `vi.importActual<typeof import('...')>` is the idiomatic mock form
			'@typescript-eslint/consistent-type-imports': OFF,
			// empty arrow stubs are normal in mocks/spies
			'@typescript-eslint/no-empty-function': OFF,
			'@typescript-eslint/no-non-null-assertion': OFF,
			'max-classes-per-file': OFF,
			'sonarjs/no-duplicate-string': OFF,
			'unicorn/consistent-function-scoping': OFF,
			'unicorn/error-message': OFF,
			// mocks legitimately pass explicit `undefined` (e.g. mockResolvedValue)
			'unicorn/no-useless-undefined': OFF,
			'vitest/expect-expect': OFF,
			'vitest/max-expects': OFF,
			'vitest/max-nested-describe': WARN,
			'vitest/no-alias-methods': ERROR,
			'vitest/no-conditional-expect': WARN,
			'vitest/no-conditional-in-test': WARN,
			'vitest/no-conditional-tests': WARN,
			'vitest/no-disabled-tests': WARN,
			'vitest/no-done-callback': WARN,
			'vitest/no-duplicate-hooks': WARN,
			'vitest/no-focused-tests': WARN,
			'vitest/no-identical-title': ERROR,
			'vitest/no-import-node-test': WARN,
			'vitest/no-standalone-expect': WARN,
			'vitest/no-test-prefixes': WARN,
			'vitest/no-test-return-statement': WARN,
			'vitest/prefer-comparison-matcher': WARN,
			'vitest/prefer-each': WARN,
			'vitest/prefer-equality-matcher': WARN,
			'vitest/prefer-hooks-in-order': WARN,
			'vitest/prefer-hooks-on-top': WARN,
			'vitest/prefer-mock-promise-shorthand': WARN,
			// toEqual is fine; forcing toStrictEqual risks breaking value checks
			'vitest/prefer-strict-equal': OFF,
			'vitest/prefer-to-be': WARN,
			'vitest/prefer-to-be-object': WARN,
			'vitest/prefer-to-contain': WARN,
			'vitest/prefer-to-have-length': WARN,
			'vitest/prefer-todo': WARN,
			'vitest/valid-title': OFF,
		},
	},
	// #endregion
];
